### ISSUE TITLE
unable to write to holding register

### ISSUE THREAD

**Issue by jpveen** [nmakel/sdm_modbus#1]
Hi Niels. Thanks for your great module!
I am trying to set this up to run from my Synology NAS. My nas had an old Python3 version, which did not work at all. With some struggle got Python 3.6.10 working, and reading now works with sdm_modbus.

However I need to change also some holding registers, but I get stuck with the following error:
ValueError: too many values to unpack (expected 7)

Any idea how I can fix this?
Thanks,
Jan-Pieter

My script looks like:
```
import sdm_modbus
# SDM120 over ModbusTCP
device = sdm_modbus.SDM120(host="192.168.1.90", port=8899)
print(device.connected())
print(device)
print(device.read("voltage"))
print(device.read_all(sdm_modbus.registerType.HOLDING))
print(device.registers["voltage"])
print(device.registers["baud"])
print(device.registers["relay_pulse_width"])
device.write("baud",2)
```

Script output:
```
True
SDM120(192.168.1.90:8899, connectionType.TCP: timeout=1, retries=3, unit=0x1)
231.39999389648438
{'demand_time': 1, 'demand_period': 60, 'relay_pulse_width': 60, 'network_parity_stop': 0, 'meter_id': 1, 'baud': 0, 'p1_output_mode': 4, 'display_scroll_timing': 0, 'p1_divisor': 0, 'measurement_mode': 0, 'indicator_mode': 0}
(0, 2, <registerType.INPUT: 1>, <registerDataType.FLOAT32: 11>, <class 'float'>, 'Voltage', 'V', 1)
(28, 2, <registerType.HOLDING: 2>, <registerDataType.FLOAT32: 11>, <class 'int'>, 'Baud Rate', [2400, 4800, 9600, -1, -1, 1200], 1)
(12, 2, <registerType.HOLDING: 2>, <registerDataType.FLOAT32: 11>, <class 'int'>, 'Relay Pulse Width', 'ms', 1)
Traceback (most recent call last):
  File "testjp.py", line 13, in <module>
    device.write("relay_pulse_width",4)
  File "/usr/local/python3/lib/python3.6/site-packages/sdm_modbus/__init__.py", line 233, in write
    return self._write(self.registers[key], data)
  File "/usr/local/python3/lib/python3.6/site-packages/sdm_modbus/__init__.py", line 210, in _write
    address, length, rtype, dtype, vtype, label, fmt = value
ValueError: too many values to unpack (expected 7)

```

**Comment by nmakel** [comment]
Hi Jan-Pieter, looks like you've run into a bug caused by the latest update. I don't have the means to resolve this today, but if you don't mind making a small modification to your local installation, please try the following:

Change line 210 in \_\_init\_\_.py from: https://github.com/nmakel/sdm_modbus/blob/e60ecc5c974ff1970fcea77552bc99b65a7125d5/sdm_modbus/__init__.py#L210

To:

`address, length, rtype, dtype, vtype, label, fmt, batch = value`

The register definitions were changed to contain a query batch number. The `_write()` function wasn't updated to reflect this, resulting in the error you're experiencing.

**Comment by nmakel** [comment]
I have just uploaded 0.4.1, which should fix this issue.

**Comment by jpveen** [comment]
Thanks Niels, works as a charm now!
